workflows:
  flutter-app-release:
    name: ResenhaApp Release
    max_build_duration: 30
    environment:
      flutter: stable
      vars:
        APP_NAME: "ResenhaApp"
        OPENAI_API_KEY: Encrypted(OPENAI_API_KEY)
        CM_KEYSTORE_PASSWORD: Encrypted(CM_KEYSTORE_PASSWORD)
        CM_KEY_ALIAS: Encrypted(CM_KEY_ALIAS)
        CM_KEY_PASSWORD: Encrypted(CM_KEY_PASSWORD)
      android_signing:
        - keystore: resenha_keystore # <== nome salvo no painel do Codemagic

    scripts:
      - name: 📝 Criar arquivo .env
        script: |
          echo "OPENAI_API_KEY=$OPENAI_API_KEY" > .env

      - name: 🔧 Instalar dependências
        script: |
          flutter pub get

      - name: ✅ Rodar testes
        script: |
          flutter test

      - name: 📦 Gerar APK Android
        script: |
          flutter build apk --release --build-name=1.0.0 --build-number=1

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/**/outputs/**/*.aab

    publishing:
      email:
        recipients:
          - seuemail@exemplo.com
        notify:
          success: true
          failure: true
