workflows:
  flutter-app-release:
    name: ResenhaApp Release
    max_build_duration: 30
    environment:
      flutter: stable
      groups: # Adicione esta seção
        - default # Especifique o grupo "default"
      vars:
        APP_NAME: "ResenhaApp"
      android_signing:
        - keystore: resenha_keystore

    scripts:
      - name: 📝 Criar arquivo .env
        script: |
          echo "OPENAI_API_KEY=$OPENAI_API_KEY" > .env
          echo "--- Conteúdo do .env gerado: ---"
          cat .env # Adicione esta linha

      - name: 🔧 Instalar dependências
        script: |
          flutter pub get

      - name: ✅ Rodar testes
        script: |
          flutter test

      - name: 📦 Gerar APK Android
        script: |
          flutter build apk --release --build-name=1.0.0 --build-number=1

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/**/outputs/**/*.aab

    publishing:
      email:
        recipients:
          - seuemail@exemplo.com
        notify:
          success: true
          failure: true
