name: resenha_app
description: "Aplicativo gerador de resenhas corrigidas para facilitar a vida dos patrulheiros do 10ºBC."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.0
  intl: ^0.20.2
  http: ^1.4.0
  flutter_dotenv: ^5.1.0
  speech_to_text: ^7.0.0
  permission_handler: ^12.0.0+1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # ✅ Apenas para builds locais (desenvolvimento)
  # Em produção, o Codemagic cria dinamicamente o .env e remove esta linha
  assets:
    - .env
